### PR TITLE
CP-15403: Add rebranding phase in xenadmin

### PR DESCRIPTION
**Pull request by cheng--zhang**
Add re-branding.sh to rebranding the resx and assembly info.

Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>

### CODE REVIEW

**Comment by cheng--zhang** [comment]
These code should be merged after xenadmin-branding.git merge to trunk.

**Comment by MihaelaStoica** [comment]
Hi Cheng, regarding BRANDING_COPYRIGHT_YEARS - We no longer include the year in our copyright notices, so the copyright property should be something like "Copyright © Citrix Systems, Ltd"

**Comment by cheng--zhang** [comment]
@MihaelaStoica 
The last commit of update xenadmin-branding is use to make sure if the remote branch have changes like pull -f that cannot merge, the build can still success.

**Comment by cheng--zhang** [comment]
Hi @MihaelaStoica 
I also add the first texture rebranding as the last code commit.
Please help to review and merge if possible.
Thanks

**Comment by cheng--zhang** [comment]
Hi @MihaelaStoica 
I have rebase the code to latest trunk and build it in my tocco project.
Result can be found here: xenadmin_rebranding-2/3149/

Please help to review and give your comments

**Comment by MihaelaStoica** [comment]
looks good. Merging

**Pull request merged**
