### PR TITLE
CA-248087: Updated API bindings.

### PR DESCRIPTION
**Pull request by kc284**
Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>

### CODE REVIEW

**Comment by kc284** [comment]
Please note there one or two small problems with this PR, namely some missing descriptions. These are to be fixed on the sdk side.

**Comment by stephen-turner** [comment]
Why have vmss_type and vmss_frequency changed? Are these just line-ending changes? If so, were they incorrect before and are correct now, or the other way round?

**Comment by kc284** [comment]
Yes, these files were originally committed with unix-style eol, now they are windows-style.
The SDK does normalise the lines, so it's likely the regression to unix eol was due to the committer's local git settings - it does happen quite often.

**Comment by stephen-turner** [comment]
OK, thanks, merging.

**Pull request merged**
