### PR TITLE
CP-12158: Read the Call Home upload schedule and determine if an uplo…

### PR DESCRIPTION
**Pull request by cheng--zhang**
…ad can start

1.Add logic to firm an upload can start.
2.Lock will be added if upload can start
3.Add unit test

Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>

### CODE REVIEW

**Comment by cheng--zhang** [comment]
Hi @MihaelaStoica 
Could you please help to review the code. Thanks.

**Comment by cheng--zhang** [comment]
Hi @MihaelaStoica 
I already update the tests to use the db you mentioned. Please help to check the new commit.
Thanks.

**Comment by cheng--zhang** [comment]
Hi @MihaelaStoica 
Thanks a lot for your detailed comments. I already modify the code based on your comments and please help to check the new commit again.
Thanks.

**Comment by MihaelaStoica** [comment]
Looks good. Merging.

**Pull request merged**
