### PR TITLE
CP-16097: Hide Thin Provosioning in XenCenter

### PR DESCRIPTION
**Pull request by GaborApatiNagy**
Commented code out only for easier reverting.

Signed-off-by: Gabor Apati-Nagy <gabor.apati-nagy@citrix.com>

### CODE REVIEW

**Comment by stephen-turner** [comment]
The change looks fine, but can I suggest putting a common string on each of the comment markers so that we can find them all again?

**Comment by GaborApatiNagy** [comment]
Yes, no problem. I will change it.

**Comment by GaborApatiNagy** [comment]
Updated

**Comment by stephen-turner** [comment]
Thanks, merging.

**Pull request merged**
