### PR TITLE
CP-7644: Write XenCenter product version and build number

### PR DESCRIPTION
**Pull request by rosslagerwall**
Write out the XenCenter version and build number into a version file so
that other tools can determine them from the build artifacts.

Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>

### CODE REVIEW

**Comment by MihaelaStoica** [comment]
I think we also need to change archive-push.sh to copy the xcversion file into xenadmin-ref repository.

**Comment by rosslagerwall** [comment]
OK, done.

**Comment by GaborApatiNagy** [comment]
Thanks Ross, this looks good.
Merging.

(I think we still need to add this new file using "hg add xcversion", I am happy to do it using the Jenkins server, probably that's the easiest way.)

**Comment by rosslagerwall** [comment]
OK, please do add it. Thanks!

**Pull request merged**
