### PR TITLE
Revert "Temporarily hide "Convert SR""

### PR DESCRIPTION
**Pull request by MihaelaStoica**
This reverts commit 127b60871c1cef6ba018b5555bdf2befc49db366.

### CODE REVIEW

**Comment by stephen-turner** [comment]
Just a revert, looks good.

**Comment by stephen-turner** [comment]
... but needs rebasing.

**Comment by MihaelaStoica** [comment]
Rebased

**Comment by stephen-turner** [comment]
Thanks, pulling now.

**Pull request merged**
