### PR TITLE
CP-20149: Some more script adjustments.

### PR DESCRIPTION
**Pull request by kc284**

### CODE REVIEW

**Comment by GaborApatiNagy** [comment]
It looks good to me, but may I suggest we use ticket numbers in (most) commits to make the history look better?

For this PR, I think it's fine if we just change the title.

**Comment by stephen-turner** [comment]
Yes, ticket numbers in all commits please (except for trivial typo corrections and the like).

**Comment by kc284** [comment]
Ok, I'll keep this in mind for the future. For the time being, can we merge this because I wouldn't like to delay it further.

**Comment by GaborApatiNagy** [comment]
I added CP-20149 to the title of this PR, so the merge commit will have it and that's more than enough imho.

**Pull request merged**
