### PR TITLE
CA-322705: Disallow re-attaching GFS2 SR if clustering is not enabled.

### PR DESCRIPTION
**Pull request by kc284**
Also minor refactoring.

### CODE REVIEW

**Comment by MihaelaStoica** [comment]
These changes only cover the HBA type, we still have the same problem for iSCSI.

We might need a stronger warning for the "Format" option, as this now becomes the default option when reattaching of the existing GFS2 SR is disabled.

**Comment by kc284** [comment]
I rebased on master hence the force-push diff has more changes and is not very useful; the first commit is intact, please review just the seccond commit.

**Comment by kc284** [comment]
Rebased on master again; 1st commit still intact, 2nd one is to be reviewed.

**Comment by kc284** [comment]
Rebased on master again; 1st commit still intact, 2nd one is to be reviewed.

**Comment by kc284** [comment]
Added one more commit, please review 2nd and 3rd.

**Comment by kc284** [comment]
I had to rebase on master again. The corrections per review are in https://github.com/xenserver/xenadmin/compare/e5acc440b3479ab38f26f1738ebf79d863b9bd66..4a5e70c8e1e22399e3185d035b36083ba647a804

**Pull request merged**
