### PR TITLE
CP-16921: Update XenCenter bindings

### PR DESCRIPTION
**Pull request by MihaelaStoica**
Signed-off-by: Mihaela Stoica <mihaela.stoica@citrix.com>

### CODE REVIEW

**Comment by kc284** [comment]
The methods in the downloader are not needed because for servers after boston we do not call DownloadObjects. We need to check why the SDK engine has generated them. In the meantime you could perhaps strip manually this chunk from the submitted code.

**Comment by MihaelaStoica** [comment]
Thanks @kc284. I've reverted the changes to the XenOnjectDownloader file.

**Comment by kc284** [comment]
One more thing that I forgot earlier - sorry!
The SR_BACKEND_FAILURE_457 seems to be absent in the xapi branch used for the generation of the above bindings, if it was purposefully added on trunk for some past feature we should restore it.

**Comment by MihaelaStoica** [comment]
The SR_BACKEND_FAILURE_457 has been removed from trunk xapi branch as well.

**Comment by kc284** [comment]
Ok, as discussed, it seems SR_BACKEND_FAILURE_457 is only left over in XC and can be removed.
Looks good, Merging.

**Pull request merged**
