### PR TITLE
L10N : Translation and resx resync

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Darren Matthews <darren.matthews@citrix.com>

### CODE REVIEW

**Comment by kc284** [comment]
I think VS is adding automatically the entries `mimetype="application/x-microsoft.net.object.bytearray.base64" ` - are they needed?

**Comment by DarrenMatthews776** [comment]
Those entries are the same as what is in the english resx file. I left them in because I didn't want to cause any unwanted side effects that was different from the English version. If they are auto generated and not needed then they wont be needed.

**Comment by MatthewsD776** [comment]
Are the <metadata> tags not needed too? Or are just the mimetype bytearray data tags the only ones not needed?

**Comment by DarrenMatthews776** [comment]
Are the metadata tags not needed too? Or just remove the mimetype data tags?

**Pull request merged**
