### PR TITLE
CP-41775: Fix using Hanja/Hangeul keys over VNC

### PR DESCRIPTION
**Pull request by rosslagerwall**

### CODE REVIEW

**Comment by rosslagerwall** [comment]
While this is not dependent on the QEMU changes, we should probably wait until the QEMU side is merged before merging this  just in case the upstream reviewers decide on a different approach.

**Review by danilo-delbusso — APPROVED** [review]

**Review by kc284 — APPROVED** [review]

**Review by CitrixChris — APPROVED** [review]

**Comment by rosslagerwall** [comment]
I think this is ready to go in now.

**Comment by danilo-delbusso** [comment]
Tested and works. Thanks @rosslagerwall 🚀 

This hasn't broken anything for existing hosts, as expected.

**Pull request merged**
