### PR TITLE
CA-293683: Prevent automatic scrolling in RPU wizard if user has scrolled manually

### PR DESCRIPTION
**Pull request by danilo-delbusso**
### 🚨 Please review each commit separately
Only the first one contains the fix.

The others are to tidy some aspects of the code.

Feel free to weigh in on the naming and/or location of `AppTextBox`, I wasn't sure what to choose for them.

_______

The basic idea here is that we're not automatically keeping the `TextBox` scrolled all the way down if the user has moved the scrollbar.
If they move it back to the bottom, it'll go back to scrolling automatically.

I have also made the event return the `newPosition` of the bar, and added _ad-hoc_ logic for the horizontal scrollbar. This is just so this event is ready for other use cases that might arise in the future.

### CODE REVIEW

**Review by kc284 — CHANGES_REQUESTED** [review]

**Comment by kc284** [comment]
Once you make the above tweaks, would it be possible to re-arrange the commits (it will probably take some conflict resolving) so that the actual bug fix is still in one commit separate from the code tidy? Because the bug fix will need porting to the lcm stream. If it is too much hassle leave it - porting can be done as re-implementation of the changes.

**Review by AaronRobson — DISMISSED** [review]

**Comment by danilo-delbusso** [comment]
> e tweaks, would it be possible to re-arrange the commits (it will probably take some conflict resolving) so that the actual bug fix is still in one commit separate from the code tidy? Because the bug fix will need porting to the lcm stream. If it is too much hassle leave it - porting can be done as re-implementation of the changes.

All done, though GitHub doesn't cope well with this so you'll need to re-review the whole PR I'm afraid.

Most changes are just tidy up work, anyway. Happy to help with any queries

**Comment by kc284** [comment]
Thanks for the corrections.
I have now checked out the code to try it out (in fact, I cherry-picked the first commit to the lcm branch where installing updates is possible) and it does not seem to work for me. When the output exceeded the window height I scrolled upwards and expected it to stay there until I scrolled down, but when new output arrived it still scrolled to the end on its own.

**Comment by danilo-delbusso** [comment]
> Thanks for the corrections. I have now checked out the code to try it out (in fact, I cherry-picked the first commit to the lcm branch where installing updates is possible) and it does not seem to work for me. When the output exceeded the window height I scrolled upwards and expected it to stay there until I scrolled down, but when new output arrived it still scrolled to the end on its own.

Thanks, I'll flag the PR as `needs updating` while I look into this

**Comment by danilo-delbusso** [comment]
Remarks about the new changes.

The issue brought up by @kc284 was the missing `-1` in `IsVerticalScrollBarAtBottom`.

While making this change I also noticed another issue. `TextBox` automatically scrolls to the top when updating its `Text` value. Hence, I added a custom method that prevents this.

**Comment by kc284** [comment]
Works ok for me now.

**Review by kc284 — APPROVED** [review]

**Review by CitrixChris — APPROVED** [review]

**Comment by kc284** [comment]
Reminder that the first and fourth commit need porting to release/stockholm/lcm.

**Pull request merged**
