### PR TITLE
CP-20712: Add support for FalconOrGreater function in XC

### PR DESCRIPTION
**Pull request by geosharath**
Signed-Off-by: Sharath Babu <sharath.babu@citrix.com>

### CODE REVIEW

**Comment by stephen-turner** [comment]
Sharath, do we have the corresponding change on the server side yet? I'm still seeing 2.1.5 in branding.hg. The reason I ask is that I'm not sure whether we want to bump it to 2.2.1 or (say) 2.2.5.

**Comment by geosharath** [comment]
@stephen-turner ill check with the Ely team and get back on the exact platform version for Ely. As far as I know it is 2.2.0 so anything beyond that would be Falcon.

**Comment by stephen-turner** [comment]
Yes, Ely is 2.2.0, but trunk is still at 2.1.5. I would like to use whichever version we first put on trunk.

**Comment by geosharath** [comment]
@stephen-turner looks like in transformer world we would not be looking at branding.hg for platform version and that wont be changed also going forward

**Comment by stephen-turner** [comment]
So where does the platform version come from?

**Comment by geosharath** [comment]
@stephen-turner the value comes from branding.git and currently its set to 2.2.50

**Comment by stephen-turner** [comment]
OK, thanks. So let's use 2.2.50 here.

**Comment by geosharath** [comment]
@stephen-turner I have updated the same

**Comment by stephen-turner** [comment]
Thanks, taking the change now.

**Pull request merged**
