### PR TITLE
merge from master

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Comment by stephen-turner** [comment]
Sorin, I don't mind merging trunk into this branch, but it doesn't merge cleanly at the moment. Do you have outstanding changes in the build branch? If not, it might be cleaner to make a new branch of the project within your personal fork.

**Comment by ssbarnea** [comment]
No worries, I am doing the merge myself manually. I just want to keep the build branch close to trunk in order to make it easier to test changes.

**Comment by stephen-turner** [comment]
@ssbarnea, this seems obsolete, and won't merge cleanly. Can we close the pull request?

**Comment by stephen-turner** [comment]
Closing as obsolete.

**Pull request closed without merging**
