### PR TITLE
CA-192640: Don't log exceptions when HealthCheck service is not insta…

### PR DESCRIPTION
**Pull request by robhoes**
…lled

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
Hmm... I think that there is something wrong with the line endings...

**Comment by robhoes** [comment]
Updated patch: fixed the line endings.

**Comment by GaborApatiNagy** [comment]
Interesting, this file seems to have and has had Unix line endings. Several files have Unix and there may still be mixed ones around... 
Probably the easiest is not to allow Visual Studio & git to convert them automatically.

**Comment by GaborApatiNagy** [comment]
:+1:

**Pull request merged**
