### PR TITLE
CA-259659: Revise the update homogeneity pool join rule

### PR DESCRIPTION
**Pull request by MihaelaStoica**
- only check the updates on the master and the new slave

Signed-off-by: Mihaela Stoica <mihaela.stoica@citrix.com>

### CODE REVIEW

**Comment by stephen-turner** [comment]
Now that we are only comparing the lists on two hosts, I suspect that the algorithm is less clear than alternatives. Would some of the suggestions on https://stackoverflow.com/questions/22173762/check-if-two-lists-are-equal work equally well and be more readable?

**Comment by MihaelaStoica** [comment]
@stephen-turner Thanks for the suggestion, Please see the new commit.

**Comment by stephen-turner** [comment]
Yes, thanks, that's much clearer now. The code looks right to me, but what dev testing have you done?

**Comment by MihaelaStoica** [comment]
I couldn't do any testing with homogenoeus updates, because we don't have any yet, but I dev tested the algorithm on a slightly modified code that ignored the `enforce_homogeneity` flag.

**Comment by stephen-turner** [comment]
OK, thanks, pulling the change.

**Pull request merged**
