### PR TITLE
Sort `.resx` strings

### PR DESCRIPTION
**Pull request by danilo-delbusso**
This applies the newly added script to the files listed below (and their L10n versions).

Plan is to rebase feature branches/affected PRs onto master once this Pr is merged.
Some merge conflicts will appear in feature branches, and will need to be resolved on a case by case basis.

./XenModel/Messages.resx
./XenModel/FriendlyNames.resx
./XenModel/InvisibleMessages.resx
./XenModel/UnitStrings.resx,
./XenOvfApi/Content.resx
./XenOvfApi/Messages.resx
./Branding/Branding.resx

### CODE REVIEW

**Comment by kc284** [comment]
There are a few files containing only whitespace changes, are these line endings?

**Review by CitrixChris — APPROVED** [review]

**Review by AaronRobson — DISMISSED** [review]

**Review by kc284 — CHANGES_REQUESTED** [review]
It seems to have changed all the line endings from windows to linux, which is a bit strange since the files were saved with powershell, and ideally we should avoid. Can you have a look, maybe there is something in the script we missed when we reviewed https://github.com/xenserver/xenadmin/pull/2915.

**Comment by danilo-delbusso** [comment]
> It seems to have changed all the line endings from windows to linux, which is a bit strange since the files were saved with powershell, and ideally should be avoided. Can you have a look, maybe there is something in the script we missed when we reviewed #2915.

Yes there was an issue. Apparently `$xml.Save($path)` just works like that. I've added some logic that formats everything into CR/LF

**Review by AaronRobson — APPROVED** [review]

**Review by CitrixChris — APPROVED** [review]

**Comment by danilo-delbusso** [comment]
Waiting for https://github.com/xenserver/xenadmin/pull/2923 to be merged.

**Comment by danilo-delbusso** [comment]
Waiting for https://github.com/xenserver/xenadmin/pull/2923 to be merged.

**Review by kc284 — APPROVED** [review]

**Pull request merged**
