### PR TITLE
CP-10929: Add per-container General-Tab to XC

### PR DESCRIPTION
**Pull request by cheng--zhang**
These code change include below items:
1.Add ports and command in DockerContainer object
2.All labels in General box are internationalized.
3.Add UUID, command, ports in General box
4.Export DockerContainer in ICache
5.Modify tab title to "Container General Properties"
6.Remove properties button.
7.Add "command" and "ports" into UpdataFrom

Basic testing been done, will do more tests based on these code change.

Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>

### CODE REVIEW

**Comment by stephen-turner** [comment]
Container port:

3-image-3

**Comment by cheng--zhang** [comment]
Hi @MihaelaStoica , this is because DockerContainer seems have bug of update information to xenobject, so I add this logic to get the correct status without change focus of dockers.
There seems a CA ticket related to this issue too.Do you suggest I also fix the CA ticket?
I also check code here:https://github.com/cheng--zhang/xenadmin/blob/master/XenModel/Network/Cache.cs#L567 but not got root cause yet.
If needed, I will check how to fix this CA tomorrow.
Thanks.

**Comment by MihaelaStoica** [comment]
I think I have a fix for the refresh issue. I have submitted a pull reguest for it here: https://github.com/xenserver/xenadmin/pull/320 - the existing objects will be updated when something changes. Also, please note that when adding new properties to the DockerContainer object, these need to be added into UpdateFrom() as well. 
If you get could pull that fix and update this commit (removing the loop and updating DockerContainer.UpdateFrom), then I would be able to quickly review and merge it. 

Thanks.

**Comment by cheng--zhang** [comment]
Hi @MihaelaStoica . Thanks you for your comments. I already remove the foreach and add "command" and "ports" into "UpdataFrom".
Please help to review the code again. Thanks.

**Comment by MihaelaStoica** [comment]
Looks good now. Merging.

**Pull request merged**
