### PR TITLE
CP-23879: XenCenter: Update RPU hotfixes for Honolulu

### PR DESCRIPTION
**Pull request by GaborApatiNagy**

### CODE REVIEW

**Comment by GaborApatiNagy** [comment]
Not completely dev-tested yet

**Comment by stephen-turner** [comment]
@GaborApatiNagy Have you verified that RPU hotfixes 001-003 have not changed uuid?

**Comment by GaborApatiNagy** [comment]
@stephen-turner I've had a look, I can confirm that the uuids in RPU001-003 have not changed.

**Comment by GaborApatiNagy** [comment]
I tested that the RPU Wizard will install RPU004 on Ely.
It will also apply this on Honolul - the operation will succeed with no error messages.

**Comment by stephen-turner** [comment]
OK, I've merged it, but have you also tested upgrade from Dundee to Honolulu?

**Pull request merged**
