### PR TITLE
CP-13123: Add two buttons on General Tab of docker container.

### PR DESCRIPTION
**Pull request by huizh**
1. Add "View Console" and "View Log" on general tab of docker container.
2. Grey the two buttons if the container runs on Windows (Server 2016) VM.

Signed-off-by: Hui Zhang <hui.zhang@citrix.com>

### CODE REVIEW

**Comment by huizh** [comment]
Hi @MihaelaStoica 
Could you please help review this commit?
Thanks.

**Comment by huizh** [comment]
Hi @MihaelaStoica,
Thanks for your review and [the comments](https://github.com/huizh/xenadmin/commit/6500786551282647bdec59c96090ee345158fafb).
I have just addressed them and updated the commit [here](https://github.com/huizh/xenadmin/commit/784804c8d8669df17e009dd8896d01c70c842759).

Hi @GaborApatiNagy,
As Mihaela is on vacation and you ever kindly discussed about the solution alternatives of this feature, could you please help review the code?
Thanks a lot.

**Comment by GaborApatiNagy** [comment]
Hi @huizh , thanks for the commits, I will have a look later today.

**Comment by GaborApatiNagy** [comment]
Thanks @huizh for this PR
I had a look, tested it. Asked Robert as well.
Merging

**Comment by huizh** [comment]
Thank you, Gabor.

**Pull request merged**
