### PR TITLE
CP-41748: Remove non-English locals from installer

### PR DESCRIPTION
**Pull request by danilo-delbusso**
There is also a matching branding PR

### CODE REVIEW

**Comment by danilo-delbusso** [comment]
Blocked because we want to merge it after:

- #3096
- #3098

**Review by CitrixChris — APPROVED** [review]

**Comment by danilo-delbusso** [comment]
Will rebase once https://github.com/xenserver/xenadmin/pull/3098 is merged and this PR is reviewed

**Comment by kc284** [comment]
So far it looks ok to me, but theoretically it's better if you rebase first, so the approval can go on the final version.

**Comment by danilo-delbusso** [comment]
Force-pushed to rebase following minor `en-us.wxl` and `Jenkinsfile` conflicts

**Review by kc284 — APPROVED** [review]

**Pull request merged**
