### PR TITLE
CA-190986: Revert "CA-178985: Removed ova.xml import from XenCenter"

### PR DESCRIPTION
**Pull request by GaborApatiNagy**
Reverts xenserver/xenadmin#746

### CODE REVIEW

**Comment by GaborApatiNagy** [comment]
Please hold on merging this until we have a build from #857

**Comment by stephen-turner** [comment]
@GaborApatiNagy, did you test this with an ova.xml file?

**Comment by GaborApatiNagy** [comment]
Not yet, but I would do it before considering this done
It was easy to use GitHub to revert the one single PR that removed this feature. Assuming it had been working before the PR, this was the easiest approach.

**Comment by GaborApatiNagy** [comment]
I am checking out this branch and going to test it soon

**Comment by GaborApatiNagy** [comment]
@stephen-turner I have just tested this on my local build, worked fine with the latest ddks.iso

**Comment by GaborApatiNagy** [comment]
@stephen-turner @MihaelaStoica 
Please feel free to go ahead with merging this if you are happy with the code - the build I was waiting for has already succeeded. (I have dev tested this and it works as expected.)

**Pull request merged**
