### PR TITLE
More general hotkey definition

### PR DESCRIPTION
**Pull request by schulz-alexander**
Use "Control+N" instead of "Ctrl+N" to be buildable on non-english operation systems

### CODE REVIEW

**Comment by kc284** [comment]
This workaround is a bit volatile because if you go afterwards and make any changes to the control's designer, visual studio will automatically reset it back to `Ctrl+N`. Check if you can get it to work by removing the shortcut completely from the resx and assigning it programmatically - and please ensure the solution is tested and working on all the supported language packs (en-us, zh-cn, ja).

**Comment by borzel** [comment]
Will look at that soon...

**Comment by borzel** [comment]
I start now working on that .. was busy last days...

**Comment by borzel** [comment]
> Check if you can get it to work by removing the shortcut completely from the resx and assigning it programmatically

Solution was easy because the suggested solution was already there. Someone just forgot to remove the shortcut definition from the resx-files.

**Pull request merged**
