### PR TITLE
CA-255547: WLB code in XenCenter: Remove all code targetting <= 6.1 XenServers

### PR DESCRIPTION
**Pull request by GaborApatiNagy**
Removed code that is no longer needed. Also removed an obsolete unit test.

Signed-off-by: Gabor Apati-Nagy <gabor.apati-nagy@citrix.com>

### CODE REVIEW

**Comment by GaborApatiNagy** [comment]
Hi @huizh , @cheng-z 
You have worked on the WLB-related code in XenCenter and are familiar with it. 
Could you take a quick look at this PR?
Thanks,
Gabor

**Comment by GaborApatiNagy** [comment]
Merged, as agreed with @MihaelaStoica 
If there is any feedback, I'll assess it in a separate PR

**Comment by cheng-z** [comment]
Sorry for the delay, we have sprint planning today.
The code looks good to me.

**Comment by GaborApatiNagy** [comment]
@cheng-z Great - thanks Cheng

**Pull request merged**
