### PR TITLE
CP-11052: Add per-container "Processes"-Tab to XC

### PR DESCRIPTION
**Pull request by huizh**
This tab will show docker process id, command and CPU time.

Signed-off-by: Hui Zhang <hui.zhang@citrix.com>

### CODE REVIEW

**Comment by MihaelaStoica** [comment]
This looks good. Some minor issues I've observed: 
1. On the DockerProcess page, please make sure that all columns are visible (without horizontal scroll) when the window is resized to minimum size. We can also make the columns resizable.
2. Please leave a bit more space between the grid and Refresh button (see SrStoragePage for an example)

**Comment by huizh** [comment]
Thanks for the review and comments.
Here I upload the new commit to address the comments.
Could you please help review it?
Much appreciate.

**Comment by MihaelaStoica** [comment]
Looks good. Merging.

**Comment by huizh** [comment]
Thanks a lot.

**Pull request merged**
