### PR TITLE
CP-20245: Wording changes for change of feature name to PVS-Accelerator 

### PR DESCRIPTION
**Pull request by MihaelaStoica**

### CODE REVIEW

**Comment by stephen-turner** [comment]
Thanks, I'll review it.

**Comment by stephen-turner** [comment]
I can't easily try it out, but the diff looks fine. Do I deduce that the RRD names have changed on the server side?

**Comment by MihaelaStoica** [comment]
Yes, the rrd names have changed in the pvsproxy supp pack. I had tested it with the new supp pack.

**Comment by stephen-turner** [comment]
Great, thanks, merging the change now.

**Pull request merged**
